### ISSUE TITLE
Nodon Smart Plug power failure push

### ISSUE THREAD

**Issue by fredrikzon** [telldus/tellstick-lua-examples#5]
Hello. I bought a Nodon Smart Plug (ASP-3-1-10) with the hope of be able to get a push or mail from my Tellstick if a power failure is happening at home. I got my Tellstick + Internet connection on UPS so even if power fails the Nodon plug would be able to send a short notice as it has this function. 

But that unit wound show up as an sensor so I can't program it with push from Telldus Live login. But after som googling I found the script under this page and got it working so I can see in the IP login and under history that the plug sends power failure notices to the TellStick. Also got the Pushover app installed in the backend and got that working if I set a plug as the on/off decider. But how can I combine the Power failure script with the pushover script? Im not so much into programing and writing codes even though I understand a little of it!

**Comment by FredrikGullberg** [comment]
Hi, 
The PowerFailure script is made so that a dummy device is turned off when a Power Failure notification is received. The dummy device can then be used to trigger an event that send push notifications. 
It's probably doable to use pushover instead, but we don't want to change to example script to use pushover since that is more advanced to set up compared to using events and push to our app.

**Comment by fredrikzon** [comment]
Hi

Yes saw that later when I read the ingress text of the power failure script. Got it working now. Perfect function!

/// Peter Fredriksson
     +4670-3440924
